version = 1

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/lihongyang108/SocketRocket"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"